[package]
name = "rusk-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


#  add lib as dependency
[dependencies]
dusk-wallet = {path ="../dusk-wallet"}